#target : dependencies
#<tab>function
build = build
Inc = .\inc\

SRC = .\src\Inventory_main.c \
.\src\Add_item.c \
.\src\Remove_item.c \
.\src\Search_item.c 


all:$(SRC) 
	gcc -g -o out $(SRC) -I $(Inc)


clean : 
	del .\out.exe

run : 
	.\out.exe

	

	